## Day 1
# Part 1

In [5]:
import numpy as np

In [41]:
depths = []

with open("depths.txt") as f:
    for depth in f.readlines():
        depths.append(int(depth.strip()))
        
depths = np.array(depths)

In [42]:
print(depths)
depths_shift = np.insert(depths, 0, depths[0])[:-1]
print(depths_shift)

delta_depths = depths - depths_shift
print(delta_depths)

n_increase = np.count_nonzero(delta_depths > 0)
print(n_increase)

[ 141  152  164 ... 2660 2671 2682]
[ 141  141  152 ... 2655 2660 2671]
[ 0 11 12 ...  5 11 11]
1184


## Part 2

In [43]:
print(len(depths))
depths_shift1 = depths[1:]
depths_shift2 = depths[2:]
print(len(depths_shift1))
print(len(depths_shift2))

# Shorten the arrays so they match the shortest
depths_cut = depths[:len(depths_shift2)]
depths_shift1_cut = depths_shift1[:len(depths_shift2)]

# Sum
depths_sum = depths_cut + depths_shift1_cut + depths_shift2

2000
1999
1998


In [44]:
# Shift and calculate delta like part 1

depths_sum_shift = np.insert(depths_sum, 0, depths_sum[0])[:-1]
print(depths_sum_shift)

delta_depths_sum = depths_sum - depths_sum_shift
print(delta_depths_sum)

n_increase_sum = np.count_nonzero(delta_depths_sum > 0)
print(n_increase_sum)

[ 457  457  479 ... 7958 7969 7986]
[ 0 22 12 ... 11 17 27]
1158
