# Day 20
## Part 1

In [1]:
import numpy as np
import scipy.ndimage

In [3]:
with open("ex1.txt") as f:
    lines = [line.strip() for line in f.readlines()]
    
algorithm = tuple(int(i) for i in lines[0].replace("#", "1").replace(".", "0"))
# print(algorithm)

image = []
for line in lines[2:]:
    line = line.replace("#", "1").replace(".", "0")
    image.append([int(i) for i in line])

image = np.array(image)
print(image)

[[1 0 0 1 0]
 [1 0 0 0 0]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [0 0 1 1 1]]


I need a function to turn a 3x3 array into a decimal number through binary.

In [4]:
test = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]])
print(int(str(101010101), 2))

def get_decimal(array):
    "Array is a 3x3 array. Returns an integer."
    binary = "".join([str(i) for i in test.flatten()])
    return int(binary, 2)

def get_algorithm(array, algorithm=algorithm):
    # array is a flat array already
    # print(array)
    # print(array.shape)
    binary = "".join([str(i) for i in array.astype(int)])
    # print(binary)
    # algo_index = get_decimal(array)
    algo_index = int(binary, 2)
    return algorithm[algo_index]

# print(get_decimal(test))
# print(get_algorithm(test.flatten(), algorithm))

341


Need to pad image by 2 layers of zeros.

In [61]:
padded = np.pad(image, 2, mode="constant", constant_values=0)
print(image)
print(padded)
cleaned = scipy.ndimage.generic_filter(padded, get_algorithm, size=(3, 3), 
                                       mode="constant", cval=0, extra_keywords={"algorithm": algorithm})
print(cleaned)

[[1 0 0 1 0]
 [1 0 0 0 0]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [0 0 1 1 1]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 1 0 0]
 [0 1 0 0 1 0 1 0 0]
 [0 1 1 0 1 0 0 1 0]
 [0 1 1 1 1 0 0 1 0]
 [0 0 1 0 0 1 1 0 0]
 [0 0 0 1 1 0 0 1 0]
 [0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [5]:
def trim_zeros(image):
    nonzeros = np.argwhere(image)
    top_left = nonzeros.min(axis=0)
    bottom_right = nonzeros.max(axis=0)
    trimmed = image[top_left[0]:bottom_right[0]+1,  # plus 1 because slice isn't
                    top_left[1]:bottom_right[1]+1]
    return trimmed

In [6]:
def enhance_image(image, algorithm, pad_value=0):
    padded = np.pad(image, 2, mode="constant", constant_values=pad_value)
    cleaned = scipy.ndimage.generic_filter(padded, get_algorithm, size=(3, 3), 
                                           mode="constant", cval=pad_value, extra_keywords={"algorithm": algorithm})
    pad_value = int(cleaned[0,0])  # top-left corner shows what the infinity is turnd into
    cleaned = trim_zeros(cleaned)
    return cleaned, pad_value

In [7]:
with open("image.txt") as f:
    lines = [line.strip() for line in f.readlines()]
    
algorithm = tuple(int(i) for i in lines[0].replace("#", "1").replace(".", "0"))
# print(algorithm)

image = []
for line in lines[2:]:
    line = line.replace("#", "1").replace(".", "0")
    image.append([int(i) for i in line])

image = np.array(image)
print(image)
pad_value = 0

for _ in range(2):
    image, pad_value = enhance_image(image, algorithm, pad_value=pad_value)
    # print(pad_value)
    
print(image)
    
print(image.sum())

[[1 1 1 ... 1 1 0]
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 1 1 0]
 ...
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [1 1 1 ... 0 1 0]]
[[0 0 1 ... 1 0 0]
 [1 1 1 ... 1 1 0]
 [1 0 1 ... 1 1 1]
 ...
 [0 1 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
5819


## Part 2

In [9]:
with open("ex1.txt") as f:
    lines = [line.strip() for line in f.readlines()]
    
algorithm = tuple(int(i) for i in lines[0].replace("#", "1").replace(".", "0"))
# print(algorithm)

image = []
for line in lines[2:]:
    line = line.replace("#", "1").replace(".", "0")
    image.append([int(i) for i in line])

image = np.array(image)
print(image)
pad_value = 0

for i in range(50):
    print(i)
    image, pad_value = enhance_image(image, algorithm, pad_value=pad_value)
    # print(pad_value)
    
print(image)
    
print(image.sum())

[[1 0 0 1 0]
 [1 0 0 0 0]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [0 0 1 1 1]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
[[0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
3351
