## Day 5

# Part 1

In [147]:
import numpy as np

In [170]:
paths = []
with open("paths.txt", "r") as f:
    for line in f.readlines():
        pair1, pair2 = line.strip().split(" -> ")
        pair1 = [int(i) for i in pair1.split(",")]
        pair2 = [int(i) for i in pair2.split(",")]
        paths.append([pair1, pair2])
        
# print(paths)

In [171]:
# We only care about straight lines in part 1 i.e. x1 = x2 OR y1 = y2
diagonals = []
indices_to_remove = []
for index, path in enumerate(paths):
    if path[0][0] != path[1][0] and path[0][1] != path[1][1]:
        indices_to_remove.append(index)
        diagonals.append(path)
        
for index in sorted(indices_to_remove, reverse=True):
    paths.pop(index)

# for path in paths:
    # print(path)

In [172]:
# need to sort paths so smaller numbers on the left
sorted_paths = []
for path in paths:
    sorted_paths.append(sorted(path, key=lambda x:sum(x)))

paths = sorted_paths[:]

# for path in paths:
#     print(path)

In [173]:
x_coords = []
y_coords = []
for path in paths:
    for coord in path:
        x_coords.append(coord[0])
        y_coords.append(coord[1])
        
max_x = max(x_coords)+1
max_y = max(y_coords)+1

field = np.zeros([max_x+1, max_y+1])

for path in paths:
    field[path[0][0]:path[1][0]+1, path[0][1]:path[1][1]+1] += 1
    
print(np.transpose(field)[:-1, :-1])

view = np.transpose(field)[:-1, :-1]
print(f"At least two vents overlap at {view[view >= 2].size} points.")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
At least two vents overlap at 6005 points.


# Part 2

In [176]:
# print(diagonals)

sorted_diags = []
for path in diagonals:
    sorted_diags.append(sorted(path, key=lambda x:sum(x)))

diagonals = sorted_diags[:]

print(field)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [175]:
# From a pair specifying a diagonal, make a list of all points that covers and then just change those?
# probably inefficient but maybe simpler
new_field = np.copy(field)

for pair in diagonals:
    if pair[0][0] > pair[1][0]:
        xs = [i for i in range(pair[0][0], pair[1][0]-1, -1)]
    else:
        xs = [i for i in range(pair[0][0], pair[1][0]+1)]

    if pair[0][1] > pair[1][1]:
        ys = [i for i in range(pair[0][1], pair[1][1]-1, -1)]
    else:
        ys = [i for i in range(pair[0][1], pair[1][1]+1)]

    # print(list(zip(xs, ys)))

    for coords in zip(xs, ys):
        field[coords] += 1
            
print(field)
view = np.transpose(field)[:-1, :-1]
print(f"At least two vents overlap at {view[view >= 2].size} points.")

field = np.copy(new_field)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
At least two vents overlap at 23864 points.
