## Day 5

# Part 1

In [147]:
import numpy as np

In [170]:
paths = []
with open("paths.txt", "r") as f:
    for line in f.readlines():
        pair1, pair2 = line.strip().split(" -> ")
        pair1 = [int(i) for i in pair1.split(",")]
        pair2 = [int(i) for i in pair2.split(",")]
        paths.append([pair1, pair2])
        
# print(paths)

In [171]:
# We only care about straight lines in part 1 i.e. x1 = x2 OR y1 = y2
diagonals = []
indices_to_remove = []
for index, path in enumerate(paths):
    if path[0][0] != path[1][0] and path[0][1] != path[1][1]:
        indices_to_remove.append(index)
        diagonals.append(path)
        
for index in sorted(indices_to_remove, reverse=True):
    paths.pop(index)

# for path in paths:
    # print(path)

In [172]:
# need to sort paths so smaller numbers on the left
sorted_paths = []
for path in paths:
    sorted_paths.append(sorted(path, key=lambda x:sum(x)))

paths = sorted_paths[:]

# for path in paths:
#     print(path)

In [173]:
x_coords = []
y_coords = []
for path in paths:
    for coord in path:
        x_coords.append(coord[0])
        y_coords.append(coord[1])
        
max_x = max(x_coords)+1
max_y = max(y_coords)+1

field = np.zeros([max_x+1, max_y+1])

for path in paths:
    field[path[0][0]:path[1][0]+1, path[0][1]:path[1][1]+1] += 1
    
print(np.transpose(field)[:-1, :-1])

view = np.transpose(field)[:-1, :-1]
print(f"At least two vents overlap at {view[view >= 2].size} points.")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
At least two vents overlap at 6005 points.


# Part 2

In [174]:
print(diagonals)

sorted_diags = []
for path in diagonals:
    sorted_diags.append(sorted(path, key=lambda x:sum(x)))

diagonals = sorted_diags[:]

print(field)

[[[561, 579], [965, 175]], [[919, 964], [70, 115]], [[122, 463], [261, 602]], [[636, 797], [797, 958]], [[371, 220], [18, 573]], [[952, 953], [72, 73]], [[13, 143], [755, 885]], [[65, 84], [839, 858]], [[656, 748], [61, 153]], [[497, 19], [310, 206]], [[686, 902], [919, 669]], [[16, 852], [843, 25]], [[945, 954], [23, 32]], [[935, 174], [485, 624]], [[12, 59], [916, 963]], [[625, 400], [507, 282]], [[943, 178], [400, 721]], [[12, 976], [900, 88]], [[104, 37], [609, 542]], [[207, 736], [800, 143]], [[956, 52], [26, 982]], [[770, 861], [915, 716]], [[948, 25], [42, 931]], [[245, 313], [748, 816]], [[946, 933], [472, 459]], [[870, 111], [50, 931]], [[770, 464], [290, 944]], [[264, 700], [941, 23]], [[19, 40], [957, 978]], [[25, 902], [684, 243]], [[300, 164], [532, 396]], [[113, 115], [962, 964]], [[251, 50], [531, 330]], [[958, 55], [41, 972]], [[985, 984], [62, 61]], [[984, 273], [370, 887]], [[271, 758], [237, 792]], [[443, 534], [835, 926]], [[810, 344], [760, 394]], [[923, 378], [415

In [175]:
# From a pair specifying a diagonal, make a list of all points that covers and then just change those?
# probably inefficient but maybe simpler
new_field = np.copy(field)

for pair in diagonals:
    if pair[0][0] > pair[1][0]:
        xs = [i for i in range(pair[0][0], pair[1][0]-1, -1)]
    else:
        xs = [i for i in range(pair[0][0], pair[1][0]+1)]

    if pair[0][1] > pair[1][1]:
        ys = [i for i in range(pair[0][1], pair[1][1]-1, -1)]
    else:
        ys = [i for i in range(pair[0][1], pair[1][1]+1)]

    # print(list(zip(xs, ys)))

    for coords in zip(xs, ys):
        field[coords] += 1
            
print(field)
view = np.transpose(field)[:-1, :-1]
print(f"At least two vents overlap at {view[view >= 2].size} points.")

field = np.copy(new_field)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
At least two vents overlap at 23864 points.
