## Day 15

# Part 1

In [7]:
import numpy as np

with open("cavern.txt") as f:
    array = np.array([[int(n) for n in line.strip()] for line in f.readlines()])
    
print(array)

[[7 1 7 ... 1 6 1]
 [4 6 4 ... 4 9 4]
 [3 2 8 ... 1 6 1]
 ...
 [7 5 1 ... 1 1 8]
 [2 2 7 ... 7 1 8]
 [1 8 1 ... 9 2 5]]


In [12]:
small_array = array[-3:, -3:]
print(small_array)

# Work with small_array while thinking of a method? :/

[[6 3 9]
 [5 2 1]
 [5 8 1]]


In [2]:
def gen_neighbours(coord, edges):
    """Return all coordinates for neighbours of a coordinate.
    Edges is (max_y, max_x).
    Coords are done numpy-style = (y, x)"""
    
    neighbours = []
        
    
    possible = ((coord[0]+1, coord[1]), (coord[0]-1, coord[1]), (coord[0], coord[1]+1), (coord[0], coord[1]-1))
    for neighbour in possible:
        if 0 <= neighbour[0] < edges[0] and 0 <= neighbour[1] < edges[1]:
            neighbours.append(neighbour)
        
    return neighbours

I have no idea what kind of method to use to solve this, so I'm just going to try one and see if I can get the answer for the small array.

### Method 1

From the end, calculate the "minimum cost" from that square to the end.

For example, the neighbours of the end will just be themselves, then the ones adjacent to those will be the minimum of their adjacents + themselves, etc.

In [38]:
# Creating min_distances array

print(small_array)
min_distances = np.full(small_array.shape, np.inf)  # use to trakc min distances?

print(min_distances)

end_coord = [small_array.shape[0]-1, small_array.shape[1]-1]
print(end_coord)
min_distances[end_coord[0], end_coord[1]] = small_array[end_coord[0], end_coord[1]]

print(small_array[end_coord[0], end_coord[1]])

print(min_distances)

# Go through coordinates

for end_neighbour in gen_neighbours(end_coord, small_array.shape):
    # generate neighbours for this one
    # set it equal to minimum neighbour + itself in small_array
    neighbours = gen_neighbours(end_neighbour, small_array.shape)
    min_value = min([min_distances[i[0], i[1]] for i in neighbours])
    min_distances[end_neighbour[0], end_neighbour[1]] = min_value + small_array[end_neighbour[0], end_neighbour[1]]
    
print(min_distances)

[[6 3 9]
 [5 2 1]
 [5 8 1]]
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[2, 2]
1
[[inf inf inf]
 [inf inf inf]
 [inf inf  1.]]
[[inf inf inf]
 [inf inf  2.]
 [inf  9.  1.]]


In [60]:
# I need to get [2, 1], [1, 2], [2, 0], [1, 1], [0, 2]

max_sum = small_array.shape[0]

neighbour_order = []
for i in range(max_sum, -1, -1):
    # print(i)
    for j in range(0, i+1):
        k = i - j
        if k < max_sum and j < max_sum:
            neighbour_order.append([k, j])
            
print(neighbour_order)

[[2, 1], [1, 2], [2, 0], [1, 1], [0, 2], [1, 0], [0, 1], [0, 0]]


In [69]:
for _ in range(2):  # need to do this twice? not sure
    for neighbour in neighbour_order:
        # generate neighbours for this one
        # set it equal to minimum neighbour + itself in small_array
        neighbours = gen_neighbours(neighbour, small_array.shape)
        min_value = min([min_distances[i[0], i[1]] for i in neighbours])
        min_distances[neighbour[0], neighbour[1]] = min_value + small_array[neighbour[0], neighbour[1]]
    
print(min_distances)
print(min_distances[0, 0])

[[13.  7. 11.]
 [ 9.  4.  2.]
 [14.  9.  1.]]
13.0


In [93]:
# Now do it for the example array

print(array)

min_distances = np.full(array.shape, np.inf)  # use to trakc min distances?
end_coord = [array.shape[0]-1, array.shape[1]-1]
min_distances[end_coord[0], end_coord[1]] = array[end_coord[0], end_coord[1]]

print(min_distances)

max_sum = (array.shape[0] - 1) + (array.shape[1] - 1)

neighbour_order = []
for i in range(max_sum, -1, -1):
    # print(i)
    for j in range(0, i+1):
        k = i - j
        if k < array.shape[0] and j < array.shape[1]:
            neighbour_order.append([k, j])
            
print(neighbour_order)
neighbour_order.remove(end_coord)

old_array = array
            
# for _ in range(5):  # need to do this twice? not sure - maybe until it stops changing?
while not np.array_equal(min_distances, old_array):
    old_array = min_distances
    for neighbour in neighbour_order:
        # generate neighbours for this one
        # set it equal to minimum neighbour + itself in small_array
        neighbours = gen_neighbours(neighbour, array.shape)
        # print(neighbour)
        min_value = min([min_distances[i[0], i[1]] for i in neighbours])
        min_distances[neighbour[0], neighbour[1]] = min_value + array[neighbour[0], neighbour[1]]
        
print(min_distances)
print(min_distances[0, 0] - array[0, 0])

[[1 1 6 3 7 5 1 7 4 2]
 [1 3 8 1 3 7 3 6 7 2]
 [2 1 3 6 5 1 1 3 2 8]
 [3 6 9 4 9 3 1 5 6 9]
 [7 4 6 3 4 1 7 1 1 1]
 [1 3 1 9 1 2 8 1 3 7]
 [1 3 5 9 9 1 2 4 2 1]
 [3 1 2 5 4 2 1 6 3 9]
 [1 2 9 3 1 3 8 5 2 1]
 [2 3 1 1 9 4 4 5 8 1]]
[[inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf  1.]]
[[9, 9], [9, 8], [8, 9], [9, 7], [8, 8], [7, 9], [9, 6], [8, 7], [7, 8], [6, 9], [9, 5], [8, 6], [7, 7], [6, 8], [5, 9], [9, 4], [8, 5], [7, 6], [6, 7], [5, 8], [4, 9], [9, 3], [8, 4], [7, 5], [6, 6], [5, 7], [4, 8], [3, 9], [9, 2], [8, 3], [7, 4], [6, 5], [5, 6], [4, 7], [3, 8], [2, 9], [9, 1], [8, 2], [7, 3], [6, 4], [5, 5], [4, 6], [

In [11]:
# Now do it for the example array

def gen_min_distances(array):
    """array is the original array"""
    
    min_distances = np.full(array.shape, np.inf)  # use to track min distances?
    end_coord = [array.shape[0]-1, array.shape[1]-1]
    min_distances[end_coord[0], end_coord[1]] = array[end_coord[0], end_coord[1]]

    max_sum = (array.shape[0] - 1) + (array.shape[1] - 1)

    neighbour_order = []
    for i in range(max_sum, -1, -1):
        # print(i)
        for j in range(0, i+1):
            k = i - j
            if k < array.shape[0] and j < array.shape[1]:
                neighbour_order.append([k, j])

    neighbour_order.remove(end_coord)

    old_array = array

    # while not np.array_equal(min_distances, old_array):  # while there's still change
    for _ in range(10):
        old_array = min_distances
        for neighbour in neighbour_order:
            # generate neighbours for this one
            # set it equal to minimum neighbour + itself in small_array
            neighbours = gen_neighbours(neighbour, array.shape)
            # print(neighbour)
            min_value = min([min_distances[i[0], i[1]] for i in neighbours])
            min_distances[neighbour[0], neighbour[1]] = min_value + array[neighbour[0], neighbour[1]]

    return min_distances

In [12]:
min_distances = gen_min_distances(array)
print(min_distances[0, 0] - array[0, 0])

435.0


## Part 2

Make the big array and then just run the same algorithm on it? :O

In [9]:
print(array)

arrays = [array]

# increased = array + 1
# print(increased)
# increased[increased == 10] = 1
# print(increased)

track_array = array.copy()

for i in range(1, 9):
    increased = track_array + 1
    increased[increased == 10] = 1
    track_array = increased.copy()
    arrays.append(increased)

[[7 1 7 ... 1 6 1]
 [4 6 4 ... 4 9 4]
 [3 2 8 ... 1 6 1]
 ...
 [7 5 1 ... 1 1 8]
 [2 2 7 ... 7 1 8]
 [1 8 1 ... 9 2 5]]


In [13]:
# test = np.array([[1, 2], [3, 4]])
# print(np.concatenate([test, test], axis=1))
print(array.shape)

rows = []

for i in range(5):
    row = [arrays[i]]
    row.extend(arrays[i+1:i+5])

    row_array = np.concatenate(row, axis=1)
    print(row_array.shape)
    rows.append(row_array)
    
big_array = np.concatenate(rows, axis=0)

print(big_array.shape)

print(big_array)

min_distances = gen_min_distances(big_array)
print(min_distances[0, 0] - big_array[0, 0])

# tried 2846, but didn't work: too high

(100, 100)
(100, 500)
(100, 500)
(100, 500)
(100, 500)
(100, 500)
(500, 500)
[[7 1 7 ... 5 1 5]
 [4 6 4 ... 8 4 8]
 [3 2 8 ... 5 1 5]
 ...
 [2 9 5 ... 9 9 7]
 [6 6 2 ... 6 9 7]
 [5 3 5 ... 8 1 4]]
2842.0
