## Day 11

# Part 1

In [94]:
import numpy as np

with open("octopuses.txt") as f:
    lines = [[int(char) for char in list(line.strip())] for line in f.readlines()]
    
field = np.array(lines)
print(field)

[[1 2 5 4 1 1 7 2 2 8]
 [4 4 1 6 8 7 3 2 2 4]
 [8 3 5 4 3 8 1 5 5 3]
 [1 3 7 2 6 3 7 6 1 4]
 [5 5 8 6 5 3 8 5 5 3]
 [7 2 1 3 3 3 3 4 2 7]
 [3 5 7 1 3 6 2 8 2 5]
 [1 6 8 1 1 2 6 2 4 3]
 [8 7 1 8 3 1 2 1 3 8]
 [5 2 5 4 2 6 6 3 4 7]]


In [95]:
def step_through(field):
    # Go through one step
    # 1: Increase all energies by 1
    field = field + 1

    # 2: Octopuses with energy > 9 flash, and loop until no more 9s
    flashes = set()
    while np.any(field > 9):
        # print(field)
        for i, j in zip(*np.where(field > 9)):
            if ((i, j)) in flashes:
                # each octopus only flashes at most once
                continue
            adjacents = set()
            field[i, j] = 0
            flashes.add((i, j))

            # get all adjacents coordinates
            for x in np.arange(max(0, i-1), min(9, i+1)+1):
                for y in np.arange(max(0, j-1), min(9, j+1)+1):
                    adjacents.add((x, y))

            adjacents.remove((i, j))

            for coord in adjacents:
                field[coord] += 1

    # 3: reset any flashed to 0
    for coord in flashes:
        field[coord] = 0

    return field, flashes

In [96]:
old_field = field.copy()

flash_count = 0

for i in range(100):
    field, flashes = step_through(field)
    flash_count += len(flashes)
    
print(flash_count)

field = old_field.copy()

1773


## Part 2

In [98]:
old_field = field.copy()
step = 0
flashes = set()

while len(flashes) != 100:
    step += 1
    field, flashes = step_through(field)

print(step)
field = old_field.copy()

494
