# Day 9

## Part 1

In [130]:
import numpy as np

with open("heightmap.txt") as f:
    heightmap = np.array([[int(char) for char in line.strip()] for line in f.readlines()])

# print(heightmap)

In [131]:
padded = np.pad(heightmap, 1, constant_values=np.max(heightmap)+1)
# print(heightmap)

diff_lr = np.diff(padded)[1:-1, :-1]
diff_rl = np.fliplr(np.diff(np.fliplr(padded))[1:-1, :-1])
diff_ud = np.diff(padded, axis=0)[:-1, 1:-1]
diff_du = np.flipud(np.diff(np.flipud(padded), axis=0)[:-1, 1:-1])
mask = (diff_lr < 0) & (diff_rl < 0) & (diff_ud < 0) & (diff_du < 0)

risk_level = (heightmap + 1) * mask
print(np.sum(risk_level))

633


## Part 2

In [88]:
# print(heightmap)
# print(mask)
# print(np.where(mask))

[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
[[False  True False False False False False False False  True]
 [False False False False False False False False False False]
 [False False  True False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True False False False]]
(array([0, 0, 2, 4], dtype=int64), array([1, 9, 2, 6], dtype=int64))


In [100]:
# print(heightmap<9)
# # print(np.where(heightmap<9))

# # I can get the indices of all the Trues here
# # Group the indices into lists depending on whether they're one more either in the x direction or y direction 
# # than something else in the list?
# indices = [[i, j] for i, j in zip(np.where(heightmap<9)[0], np.where(heightmap<9)[1])]
# print(indices)

[[ True  True False False False  True  True  True  True  True]
 [ True False  True  True  True False  True False  True  True]
 [False  True  True  True  True  True False  True False  True]
 [ True  True  True  True  True False  True  True  True False]
 [False  True False False False  True  True  True  True  True]]
[[0, 0], [0, 1], [0, 5], [0, 6], [0, 7], [0, 8], [0, 9], [1, 0], [1, 2], [1, 3], [1, 4], [1, 6], [1, 8], [1, 9], [2, 1], [2, 2], [2, 3], [2, 4], [2, 5], [2, 7], [2, 9], [3, 0], [3, 1], [3, 2], [3, 3], [3, 4], [3, 6], [3, 7], [3, 8], [4, 1], [4, 5], [4, 6], [4, 7], [4, 8], [4, 9]]


In [135]:
from scipy import ndimage

walls = heightmap<9
walls = walls.astype(int)

labelled, count = ndimage.label(walls)

areas = []

for i in range(count):
    areas.append(np.sum(walls[labelled == i + 1]))

print(np.prod(sorted(areas)[-3:]))

1050192


In [ ]:
# Start with first one

In [64]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a < 3)

b = np.array([-1, 1, -1])
c = np.array([-1, 1, 1])

print(b < 0)
print(c < 0)
print((b < 0) & (c < 0))

[[1 2 3]
 [4 5 6]]
[[ True  True False]
 [False False False]]
[ True False  True]
[ True False False]
[ True False False]
