## Day 4

# Part 1

In [78]:
import numpy as np

In [135]:
commands = []
with open("bingo.txt", "r") as f:
    file_input = [line.strip() for line in f.readlines()]

# First line is numbers
bingo_numbers = [int(i) for i in file_input.pop(0).split(",")]
file_input.pop(0)
# print(bingo_numbers)
# print(file_input)

bingo_cards = []
original_cards = []

card = []

for line in file_input:
    if line == "":
        # deal with ending card
        bingo_cards.append(np.array(card))
        original_cards.append(np.array(card))
        card = []
    else:
        numbers = line.split(" ")
        # single digits have an extra space in them, annoyingly
        while "" in numbers:
            numbers.remove("")
            
        card.append([int(i) for i in numbers])
else:
    bingo_cards.append(np.array(card))
    original_cards.append(np.array(card))

Now I have all of the bingo cards in a list.

Time to go through each using the bingo numbers and see where gets a match first.

My plan is to replace matched numbers with -1, and then sum using np.sum each row and then column until I get one that sums to -5.
Then, take the sum of the remaining numbers in the array plus the number of matched numbers, and multiply by the current number being considered.

In [136]:
# First, check there is no -1 since that'll break everything
for card in bingo_cards:
    if -1 in card:
        print("uh oh!!!!")
        
if -1 in bingo_numbers:
    print("uh oh!!!")

In [143]:
print(bingo_cards[0])
print(np.sum(bingo_cards[0], 0))  # does a sum by vertical lines
print(np.sum(bingo_cards[0], 1))  # does a sum by horizontal lines

[[63  5 10 69 57]
 [64 88 27 40 76]
 [59 20 58 90  6]
 [74 32 72 16 26]
 [50 17  7 93 94]]
[310 162 174 308 259]
[204 295 233 220 261]


In [142]:
board_won = False
for number in bingo_numbers:
    for card in bingo_cards:
        card[card == number] = -1
        # Check if line is complete
        if -5 in np.sum(card, 0) or -5 in np.sum(card, 1):
            numbers_remaining = np.sum(card) - np.sum(card[card == -1])  # plus 5 due to the marked numbers being -1
            board_won = True
            
            print(card)
            print("numbers remaining", numbers_remaining)
            print("number", number)
            
            print("A board won!")
            print(f"answer is {numbers_remaining * number}")
            break
            
    if board_won:
        break
        
bingo_cards = [np.copy(array) for array in original_cards]

[[54 41 -1 33 60]
 [85 -1 -1 77 51]
 [81 12 -1 20 27]
 [36 24 -1 -1 80]
 [14 83 -1 50 91]]
numbers remaining 919
number 49
A board won!
answer is 45031


# Part 2

In [134]:
commands = []
with open("ex1.txt", "r") as f:
    file_input = [line.strip() for line in f.readlines()]

# First line is numbers
bingo_numbers = [int(i) for i in file_input.pop(0).split(",")]
file_input.pop(0)
# print(bingo_numbers)
# print(file_input)

bingo_cards = []
original_cards = []

card = []

for line in file_input:
    if line == "":
        # deal with ending card
        bingo_cards.append(np.array(card))
        original_cards.append(np.array(card))
        card = []
    else:
        numbers = line.split(" ")
        # single digits have an extra space in them, annoyingly
        while "" in numbers:
            numbers.remove("")
            
        card.append([int(i) for i in numbers])
else:
    bingo_cards.append(np.array(card))
    original_cards.append(np.array(card))

In [133]:
board_won = False
remove_card = False
for number in bingo_numbers:
    cards_to_remove = []
    for index, card in enumerate(bingo_cards):
        card[card == number] = -1
        # Check if line is complete
        if -5 in np.sum(card, 0) or -5 in np.sum(card, 1):
            if len(bingo_cards) > 1:
                # print(len(bingo_cards))
                remove_card = True
                cards_to_remove.append(index)
            else:
                numbers_remaining = np.sum(card) - np.sum(card[card == -1])  # plus 5 due to the marked numbers being -1

                board_won = True

                print(card)
                print("numbers remaining", numbers_remaining)
                print("number", number)

                print("The last board won.")
                print(f"answer is {numbers_remaining * number}")
                break
            
    if remove_card:
        for i in sorted(cards_to_remove, reverse=True):
            bingo_cards.pop(i)
        remove_card = False
        
    if board_won:
        break
        
bingo_cards = [np.copy(array) for array in original_cards]

[[ 3 15 -1 -1 22]
 [-1 18 -1 -1 -1]
 [19  8 -1 25 -1]
 [20 -1 -1 -1 -1]
 [-1 -1 -1 12  6]]
numbers remaining 148
number 13
The last board won.
answer is 1924
[array([[22, 13, 17, 11,  0],
       [ 8,  2, 23,  4, 24],
       [21,  9, 14, 16,  7],
       [ 6, 10,  3, 18,  5],
       [ 1, 12, 20, 15, 19]]), array([[ 3, 15,  0,  2, 22],
       [ 9, 18, 13, 17,  5],
       [19,  8,  7, 25, 23],
       [20, 11, 10, 24,  4],
       [14, 21, 16, 12,  6]]), array([[14, 21, 17, 24,  4],
       [10, 16, 15,  9, 19],
       [18,  8, 23, 26, 20],
       [22, 11, 13,  6,  5],
       [ 2,  0, 12,  3,  7]])]
